# Generated by Django 3.1.6 on 2021-02-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocShopApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('country_code', models.BigIntegerField()),
                ('phone_number', models.FloatField()),
                ('password', models.TextField()),
            ],
        ),
    ]
