# Generated by Django 3.1.6 on 2021-02-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocShopApp', '0002_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='docshopapp',
            name='date_joined',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='docshopapp',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
