# Generated by Django 3.1.6 on 2021-02-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocShopApp', '0003_auto_20210220_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docshopapp',
            name='date_joined',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
