# Generated by Django 3.1.6 on 2021-02-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocShopApp', '0005_auto_20210220_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docshopapp',
            name='date_joined',
        ),
    ]
